
<?php
 $page_title = 'Capital Cove - Who We Are';
 include 'includes/pagehead.php';
?>

<div class="site-body">


	<div class="pe-spacer size70"></div>

	<div class="pe-container">

		<div class="row-fluid">

			<!--main content-->
			<section class="span8">

				<!--new post-->
				<div class="row-fluid">
					<div class="span12">
						<div class="post single">
							<!--post titles-->
							<div class="row-fluid">
								<div class="span12 post-title">
									<h1><a href="#">Who We Are</a></h1>
								</div>
							</div>
							<!--meta-->

<!--post image-->
							<div class="row-fluid">
								<div class="span12  post-image">
									<a href="#"><img src="img/content/WhoWeAre.jpg" class="peLazyLoading" data-original="img/content/WhoWeAre.jpg" width="620" height="349" alt="alt text" /></a>
								</div>
							</div>

							<div class="row-fluid">
								<div class="span12">
									<div class="span12">
										<p class="intro">

                                          <p>

                  <h3>    Corporate Snapshot </h3>

Capital Cove Financial is a client-focused and solutions-based Investment Advisory firm focused exclusively on REO Financial Services and Distressed Real Estate Assets. Our integrated business model combines world-class REO investment, asset management and financial services expertise with exceptional client service, in-depth consulting and the broadest array of high-yield investment opportunities. Since inception, the firm has excelled at sourcing, acquiring, managing and disposing of distressed REO Real Estate and Mortgage Portfolio assets on behalf of its own corporate portfolio, private lenders, investors, private equity funds and Limited Partner firms. And to date, the firm has consistently delivered an extensive and verifiable track record of successful transaction closings in every major REO Asset Class. Capital Cove is a Certified Minority Business Enterprise, licensed brokerage, registered investment advisor, FINRA member and SEC registered Fund Manager.
                      </p>

                       <p>

                  <h3>    Investment Acquisition, Management and Disposition Strategies </h3>

Capital Cove's unique, comprehensive approach to every investor and owner client engagement is as true business partners and trusted advisors in every sense of the term – providing more than just transactional capabilities, brokerage services or special assets lending. Our mission is to provide our clients with not only the professional services required of a full-service REO Financial Services firm, but to also offer the most innovative financing solutions to their most demanding REO acquisition and disposition challenges. From initial sourcing through the executed contract stage, we invest our focused expertise on providing tangible value to your transactions.
                      </p>

                      <p>
                       <h3>    REO Real Estate, Asset Management and Private Equity Funds </h3>

In addition to the Capital Cove REO Opportunities Fund, the firm is a leading sponsor of real estate investment programs that provide individual and institutional investors with direct access to managed REO investment accounts, foreclosure investment opportunities and distressed mortgage portfolios across a broad spectrum of REO asset classes. These real estate investment vehicles include REO fixed income plans, self-directed IRAs, real estate funds, private equity funds, trust deed investments, equity joint ventures and structured real estate financing.
                      </p>

                      <p>
                                      <h3>   Professional Short Sale Solutions & Foreclosure Lending Opportunities </h3>

Capital Cove delivers straightforward, profitable solutions for investing in today's distressed real estate market, private mortgage funds and approved short sales generated by the firm's Short Sale Management Center. Through its internal operating units and Asset Management Group teams, we work closely and collaboratively with distressed property owners, financial advisors, national asset managers, lenders, investors, alternative investment management firms and other equity stakeholders to help them identify, mitigate, fund and dispose of their REO Real Estate and troubled mortgage portfolio assets – better, faster, more profitably and with less risk than any other firm.
                      </p>


                      <h3>Our Trusted Advisors and Management Consultant team members have Cutting-edge experience in:</h3>
										  <blockquote>
                        <p>
                          <ul class="blockquote_list">
                            <li>
 Professional Short Sales and Foreclosure Workouts                            </li>

                            <li>
                             Private Mortgage Funds and Lending Programs
                            </li>
                            <li>
                            REO Financial Services & Default Services
                            </li>
                            <li>
                            Residential and Commercial Real Estate Services
                            </li>
                            <li>
                            REO Real Estate Funds | Private Equity Funds
                            </li>
                            <li>
                           REO Asset Management and Portfolio Consulting
                            </li>

                              <li>
                           Investment Management/Separately Managed Accounts
                            </li>


                              <li>
                           Direct Foreclosure and Approved Short Sale Investments
                            </li>

                                        <li>
                          Structured Finance and Equity Joint Ventures
                            </li>

                              <li>
                          Investor & Lender Foreclosure Relief Services
                            </li>

                          </ul>
                        </p>
                      </blockquote>

                    			  <p>
                                  Everyday, the real estate, asset management and alternative Investment professionals of Capital Cove approach every client engagement as true business partners and trusted advisors in every sense of the term.
Since inception, our firm has consistently delivered superior REO Portfolio Investment performance and grown the wealth of our Private and Institutional clients. We implement these strategic goals through a highly disciplined, competent and entrepreneurial approach to Foreclosure investing. From initial asset sourcing, management and acquisition of distressed REO portfolio assets to final disposition and successful investment exits – Capital Cove is steadfastly committed to Principal Owners, Investors and Equity Stakeholders in Default – Not Distress℠
To find out how to invest in REO Real Estate Fund Opportunities, Private Mortgages, or the Capital Cove REO Opportunities Fund with confidence, please contact us at: <strong>  909-457-8440   or email us at:   inquiries@capitalcove.com. </strong>
                          </p>


									</div>
								</div>
							</div>

						</div>

					</div>
				</div>
				<!--end post-->





			</section>

			<!--sidebar-->
				<?php REQUIRE 'includes/sidebar.php';?>
			<!--end sidebar-->

		</div><!--end row 1-->



	</div>
</div>



 	<div class="pe-spacer size100"></div>
	 	<?php REQUIRE 'includes/footer.php';?>